spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/birdpark
    password: Start123!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      org:
        hibernate:
          logging:
            LoggerFactory: org.hibernate.logging.internal.StandardServiceRegistryImpl
            level: ERROR
    hibernate:
      ddl-auto: update
  server:
    tomcat:
      max-http-header-size: 102400
